version: '2'
services:
  web:
    build: .
    container_name: web
    ports:
      - "3000:3000"
    links:
      - 'rethinkdb1'
      - 'rethinkdb2:some-weird-host'
      - 'rethinkdb2:something'
      - 'rethinkdb3:three-changing-the-weird-host' # http://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid
      - 'rethinkdb4:three-changing-the-hostname' # http://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid
    environment:
      - PORT=3000
      - RETHINKDB_3_1=rethinkdb3
      - RETHINKDB_3_2=three-changing-the-weird-host
      - RETHINKDB_4_3=rethinkdb4
    env_file:
      - env/some-environment-name/.env
  rethinkdb1:
    image: 'rethinkdb'
  rethinkdb2:
    image: 'rethinkdb'
  rethinkdb3:
    image: 'rethinkdb'
  rethinkdb4:
    image: 'rethinkdb'



