version: '2'
services:
  web:
    build: .
    container_name: web
    ports:
      - "3000:3000"
    links:
      - 'rethinkdb1'
      - 'rethinkdb2:some-weird-host'
      - 'rethinkdb3:another1.super_weird.00host' # http://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid
      - 'rethinkdb4:omg.not.another.one' # http://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid
    environment:
      - PORT=3000
      - RETHINKDB_3=another1.super_weird.00host
    env_file:
      - env/some-environment-name/.env
  rethinkdb1:
    image: 'rethinkdb'
  rethinkdb2:
    image: 'rethinkdb'
  rethinkdb3:
    image: 'rethinkdb'
  rethinkdb4:
    image: 'rethinkdb'
